apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ .Release.Name }}-backend

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5001